name: Lucia spark listener ci
run-name: ${{ github.actor }} run ci for Lucia spark listener ğŸš€
on: [push]

jobs:
  lucia-spark-listener-pipeline:
    runs-on: ubuntu-latest

    steps:
      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - uses: actions/checkout@v3
      - run: echo "ğŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "ğŸ–¥ï¸ The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
+     - uses: olafurpg/setup-scala@v11
      - name: compile
        run: sbt compile
      - run: echo "ğŸ This job's status is ${{ job.status }}."
